import type { ExchangeWallet } from './types'

export const EXCHANGES: ExchangeWallet[] = [
  {
    name: 'GATE.IO',
    address: 'BYBYFUMBVLPUCANXEXTSKVMGFCJBMTLPPOFVPNSATABMWDGTMFXPLZLBCXJL'
  },
  {
    name: 'Tradeogre',
    address: 'IZTNWDKXSFULQADTOLTMLUPHSCFCXLOJMQOUHPBSRGQZMMXZCJYQFTRDOGRE'
  },
  {
    name: 'Tradeogre',
    address: 'GBXUREVUSESZWAFCHPESIYLBBODDFFFZJUXUGJAJIFPFHMJSJRGQHONDGQFL'
  },
  {
    name: 'Tradeogre',
    address: 'BKCTLMGCIUAADAZQVCQCOFTGCYRDIKQRUYKWYKLEGHBELRBDLIQGRWAGFWQD'
  },
  {
    name: 'Tradeogre',
    address: 'NUJKVAKTLNMHMFMBZCXSHCLBYRPCTZVOWPWXGRTKLARFUTBVTPVELHBHYAHL'
  },
  {
    name: 'Tradeogre',
    address: 'XXIOIPKQRCJIMAVIXQQTRWQVPKPCOUSHVUPPRWDSDDXYSKTJOHUKXZICPRDA'
  },
  {
    name: 'Tradeogre',
    address: 'ETAWVIXKLVEBCFCNJBNFWMMZFGOAKBXTMARNBWYIKECASQWWBEXODQWBVBGK'
  },
  {
    name: 'Safetrade',
    address: 'VFWIEWBYSIMPBDHBXYFJVMLGKCCABZKRYFLQJVZTRBUOYSUHOODPVAHHKXPJ'
  },
  {
    name: 'Safetrade',
    address: 'CORSXCFMCTVSECCTNFEERFVUPTKDRGKALTIOWKLXSBQCSIGNTUGEKOXDNUGK'
  },
  {
    name: 'Safetrade',
    address: 'EMSSYMCBMVXSSBZZDFFNLYTVZBVBWQNAWIEDYZLBDCFYIBAKFUOOGWLAEXCL'
  },
  {
    name: 'Safetrade',
    address: 'WTBHNKRMCBHKNGZAUQQQRTUOTPRAXRQTMSJKZLFKHABABZDDNDXIZXZGNJXE'
  },
  {
    name: 'Safetrade',
    address: 'CLJHHZVRWAVBEAECXMCEIZOZOJLAMWCQMNYXXHQXOBGRUCXKVZCMBQECQJPE'
  },
  {
    name: 'MEXC',
    address: 'VUEYKUCYYHXKDGOSCWAIEECECDBCXVUSUAJRVXUQVAQPGIOABLGGLXDAXTNK'
  },
  {
    name: 'BITGET',
    address: 'EXNRRBDPYFQPXFPXCMUHZVEEBRQCBEAUDYUBHKGTRCKHVSRAQXWHQCXDLZXL'
  }
]

export const EXCHANGES_SKELETON_ROWS = EXCHANGES.length
